#!/usr/bin/env node
/**
 * Reads Input_Freigabecockpit_V2.xlsx and generates src/data/records.generated.ts
 * Run manually: node scripts/excel-to-ts.mjs
 * Also runs automatically via Vite watcher when the xlsx file changes.
 */
import ExcelJS from 'exceljs';
import { writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const XLSX_PATH = resolve(__dirname, '..', 'Input_Freigabecockpit_V2.xlsx');
const OUTPUT_PATH = resolve(__dirname, '..', 'src', 'data', 'records.generated.ts');

/**
 * Column mapping (1-indexed, matching Excel column positions):
 *  1  Zeile
 *  2  HVS-Cluster
 *  3  Speichertyp
 *  4  Speicher
 *  5  Penthouse
 *  6  Bauphase
 *  7  i-Stufe
 *  8  Lead-Stufe
 *  9  SOP
 * 10  META (Master)
 * 11  SW-Stand
 * 12  Meilenstein
 * 13  Kalenderwoche
 * 14  Ziel-Datum RSTB/Verbund
 * 15  SWL-C Upload @EE-TPL
 * 16  WMM Link
 * 17  Freigabe Level Soll
 * 18  Freigabe Level (confirmed)
 */

function formatDate(val) {
    if (val instanceof Date) {
        const y = val.getFullYear();
        const m = String(val.getMonth() + 1).padStart(2, '0');
        const d = String(val.getDate()).padStart(2, '0');
        return `${y}-${m}-${d}`;
    }
    if (val && typeof val === 'string' && val.trim()) return val.trim();
    return null;
}

function str(val) {
    if (val == null) return '';
    if (typeof val === 'object' && 'richText' in val) {
        return val.richText.map(r => r.text).join('');
    }
    return String(val).trim();
}

/**
 * Normalise FreigabeLevel strings from Excel to the canonical set.
 * Maps legacy values to the new 16-level system.
 */
const LEVEL_ALIASES = {
    // Legacy / Excel shorthand → canonical level
    'Nicht bedient': 'Nicht gesetzt',
    'RTSB Freigegeben': 'RTSB freigegeben',
    'L1': 'L1 Erstfreigabe',
    'L2': 'L2 Erstfreigabe',
    'L3': 'L3 Erstfreigabe',
    'L4': 'L4 Erstfreigabe',
};

function normaliseLevel(raw) {
    if (!raw) return 'Nicht gesetzt';
    return LEVEL_ALIASES[raw] ?? raw;
}


async function main() {
    if (!existsSync(XLSX_PATH)) {
        console.log('⚠️  Excel file not found, skipping generation (using existing records.generated.ts)');
        return;
    }
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.readFile(XLSX_PATH);

    const sheet = workbook.getWorksheet(1);
    if (!sheet) throw new Error('No worksheet found in Freigabecockpit.xlsx');

    const records = [];
    let rowIdx = 0;

    sheet.eachRow((row, rowNumber) => {
        // Row 1 = merged category headers, Row 2 = column names → skip both
        if (rowNumber <= 2) return;

        const c = row.values; // 1-indexed array

        // Normalise Kalenderwoche: Excel stores "04_2026" → we need "KW04_2026"
        const rawKW = str(c[13]);
        if (!rawKW) return; // skip empty rows
        const kalenderwoche = rawKW.startsWith('KW') ? rawKW : `KW${rawKW}`;

        const freigabeLevelSoll = normaliseLevel(str(c[17]));
        const confirmedLevel = normaliseLevel(str(c[18]));

        records.push({
            id: `${kalenderwoche}-${rowIdx++}`,
            zeile: Number(c[1]) || 0,
            hvsCluster: str(c[2]),
            speichertyp: str(c[3]),
            speicher: str(c[4]),
            penthouse: str(c[5]),
            bauphase: str(c[6]),
            iStufe: str(c[7]),
            leadStufe: str(c[8]),
            sop: str(c[9]),
            metaMaster: Number(c[10]) || 0,
            swStand: str(c[11]),
            meilenstein: str(c[12]),
            kalenderwoche,
            zieldatumRSTB: formatDate(c[14]),
            swlcUpload: formatDate(c[15]),
            wmmLink: str(c[16]),
            freigabeLevelSoll,
            confirmedLevel,
        });
    });

    // Deduplicate: the V2 Excel contains duplicate rows (e.g. C0.9, C1.0 appear twice)
    // Use composite key: zeile + speicher + kalenderwoche
    const seen = new Set();
    const uniqueRecords = records.filter(r => {
        const key = `${r.zeile}|${r.speicher}|${r.kalenderwoche}`;
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
    });

    // Generate TypeScript file
    const tsContent = `// AUTO-GENERATED from Input_Freigabecockpit_V2.xlsx — DO NOT EDIT MANUALLY
// Re-generated by: node scripts/excel-to-ts.mjs
// Last updated: ${new Date().toISOString()}

import type { FreigabeRecord, FreigabeLevel } from '../types';

export const EXCEL_RECORDS: FreigabeRecord[] = ${JSON.stringify(uniqueRecords, null, 2)} as FreigabeRecord[];

/** Total number of data rows read from Excel */
export const RECORD_COUNT = ${uniqueRecords.length};

/** Unique KW keys found in the data */
export const KW_KEYS: string[] = ${JSON.stringify([...new Set(uniqueRecords.map(r => r.kalenderwoche))])};

/** Unique Speicher values found in the data */
export const SPEICHER_LIST: string[] = ${JSON.stringify([...new Set(uniqueRecords.map(r => r.speicher))])};

/** Unique Speichertyp values found in the data */
export const SPEICHERTYP_LIST: string[] = ${JSON.stringify([...new Set(uniqueRecords.map(r => r.speichertyp))])};

/** Unique HVS-Cluster values found in the data */
export const HVS_CLUSTER_LIST: string[] = ${JSON.stringify([...new Set(uniqueRecords.map(r => r.hvsCluster))])};

/** Unique Freigabe Levels (Soll) found in the data */
export const FREIGABE_LEVELS_SOLL: FreigabeLevel[] = ${JSON.stringify([...new Set(uniqueRecords.map(r => r.freigabeLevelSoll))])} as FreigabeLevel[];

/** Unique Confirmed Levels found in the data */
export const CONFIRMED_LEVELS: FreigabeLevel[] = ${JSON.stringify([...new Set(uniqueRecords.map(r => r.confirmedLevel))])} as FreigabeLevel[];
`;

    writeFileSync(OUTPUT_PATH, tsContent, 'utf-8');
    console.log(`✅ Generated ${OUTPUT_PATH}`);
    console.log(`   ${uniqueRecords.length} records (${records.length - uniqueRecords.length} duplicates removed), ${[...new Set(uniqueRecords.map(r => r.kalenderwoche))].length} KWs, ${[...new Set(uniqueRecords.map(r => r.speicher))].length} Speicher`);
}

main().catch(err => {
    console.error('❌ Failed to generate records:', err);
    process.exit(1);
});
